using System.Collections.Generic;


namespace SagaDB.Iris
{
    public enum ReleaseAbility
    {
        HP_MAX_UP,
        HP_PER_UP,
        MP_MAX_UP,
        MP_PER_UP,
        SP_MAX_UP,
        SP_PER_UP,
        HP_REC_UP,
        MP_REC_UP,
        SP_REC_UP,
        SKILL_MP_PER_DOWN,
        SKILL_SP_PER_DOWN,
        STR_UP,
        DEX_UP,
        INT_UP,
        VIT_UP,
        AGI_UP,
        MAG_UP,
        ATK_FIX_UP,
        ATK_PER_UP,
        MATK_FIX_UP,
        MATK_PER_UP,
        SHIT_FIX_UP,
        SHIT_PER_UP,
        LHIT_FIX_UP,
        LHIT_PER_UP,
        SAVOID_FIX_UP,
        SAVOID_PER_UP,
        LAVOID_FIX_UP,
        LAVOID_PER_UP,
        DEF_UP,
        DEF_PER_UP,
        MDEF_FIX_UP,
        MDEF_PER_UP,
        WEAPON_FIX_UP,
        WEAPON_PER_UP,
        EQUIP_DEF_FIX_UP,
        EQUIP_DEF_UP,
        HIT_UP,
        AVOID_UP,
        BDAMAGE_DOWN,
        MDAMAGE_DOWN,
        ELMDMG_PER_DWON,
        PT_DAMUP,
        PT_DAMDOWN,
        HELL_DAMUP,
        HELL_DAMDOWN, 
        CRITICAL_UP, 
        CRIAVOID_UP, 
        GUARD_UP, 
        PAYLOAD_UP, 
        CAPACITY_UP, 
        LV_DIFF_DOWN, 
        REGI_POISON_UP, 
        REGI_STONE_UP,
        REGI_SLEEP_UP,
        REGI_SILENCE_UP,
        REGI_SLOW_UP, 
        REGI_CONFUSION_UP,
        REGI_ICE_UP, 
        REGI_STUN_UP,
        CAN_BTPDOWN_PER,
        P_CSPD_PER_DOWN,
        P_CSPD_PER_UP,
        M_CSPD_PER_DOWN,
        M_CSPD_PER_UP, 
        LV_DIFF_UP, 
        PART_R_HPHEAL_UP,
        PART_R_HPMAX_FIX_UP,
        PART_R_HPMAX_UP, 
        PART_MPHEAL_FIX_UP, 
        PART_MPMAX_FIX_UP,
        PART_MPMAX_UP, 
        PART_SPHEAL_FIX_UP, 
        PART_SPMAX_FIX_UP, 
        PART_SPMAX_UP, 
        PART_ATK_FIX_UP, 
        PART_ATK_PER_UP, 
        PART_MATK_FIX_UP, 
        PART_MATK_PER_UP, 
        PART_DEF_MINUS_FIX_UP,
        PART_DEF_PER_FIX_UP, 
        PART_MDEF_MINUS_FIX_UP,
        PART_MDEF_PER_FIX_UP,
        PART_MOVESPEED_UP, 
        PART_EXP_UP, 
        PART_RELIANCE_HUMAN, 
        PART_RELIANCE_BIRD, 
        PART_RELIANCE_ANIMAL,
        PART_RELIANCE_INSECT,
        PART_RELIANCE_MAGIC_CREATURE,
        PART_RELIANCE_PLANT,
        PART_RELIANCE_WATER_ANIMAL,
        PART_RELIANCE_MACHINE,
        PART_RELIANCE_ROCK, 
        PART_RELIANCE_ELEMENT, 
        PART_RELIANCE_UNDEAD, 
        PART_FOODTIME_PER, 
        PART_DEATHPENA_TIME_FIX, 
        ELEMENT_ADD_DARK, 
        ELEMENT_ADD_LIGHT, 
        ELEMENT_ADD_FIRE, 
        ELEMENT_ADD_WATER, 
        ELEMENT_ADD_EARTH, 
        ELEMENT_ADD_WIND, 
        DUR_DAMAGE_DOWN, 
        CHGSTATE_RATE_UP, 
        FOOD_UP, 
        POTION_UP, 
        DAMUP_HUMAN,
        DAMUP_BIRD,
        DAMUP_ANIMAL, 
        DAMUP_INSECT,
        DAMUP_MAGIC_CREATURE,
        DAMUP_PLANT, 
        DAMUP_WATER_ANIMAL,
        DAMUP_MACHINE, 
        DAMUP_ROCK, 
        DAMUP_ELEMENT, 
        DAMUP_UNDEAD, 
        DAMDOWN_HUMAN,
        DAMDOWN_BIRD, 
        DAMDOWN_ANIMAL,
        DAMDOWN_INSECT, 
        DAMDOWN_MAGIC_CREATURE,
        DAMDOWN_PLANT, 
        DAMDOWN_WATER_ANIMAL,
        DAMDOWN_MACHINE, 
        DAMDOWN_ROCK,
        DAMDOWN_ELEMENT,
        DAMDOWN_UNDEAD, 
        EXP_HUMAN, 
        EXP_BIRD, 
        EXP_ANIMAL,
        EXP_INSECT, 
        EXP_MAGIC_CREATURE, 
        EXP_PLANT, 
        EXP_WATER_ANIMAL,
        EXP_MACHINE, 
        EXP_ROCK,
        EXP_ELEMENT, 
        EXP_UNDEAD, 
        JEXP_HUMAN, 
        JEXP_BIRD, 
        JEXP_ANIMAL,
        JEXP_INSECT,
        JEXP_MAGIC_CREATURE,
        JEXP_PLANT, 
        JEXP_WATER_ANIMAL,
        JEXP_MACHINE, 
        JEXP_ROCK, 
        JEXP_ELEMENT,
        JEXP_UNDEAD,
        HIT_HUMAN, 
        HIT_BIRD, 
        HIT_ANIMAL,
        HIT_INSECT,
        HIT_MAGIC_CREATURE,
        HIT_PLANT, 
        HIT_WATER_ANIMAL,
        HIT_MACHINE, 
        HIT_ROCK, 
        HIT_ELEMENT,
        HIT_UNDEAD, 
        AVOID_HUMAN, 
        AVOID_BIRD, 
        AVOID_ANIMAL, 
        AVOID_INSECT,
        AVOID_MAGIC_CREATURE, 
        AVOID_PLANT, 
        AVOID_WATER_ANIMAL, 
        AVOID_MACHINE, 
        AVOID_ROCK,
        AVOID_ELEMENT,
        AVOID_UNDEAD, 
        CRITICAL_HUMAN,
        CRITICAL_BIRD,
        CRITICAL_ANIMAL, 
        CRITICAL_INSECT,
        CRITICAL_MAGIC_CREATURE,
        CRITICAL_PLANT, 
        CRITICAL_WATER_ANIMAL, 
        CRITICAL_MACHINE, 
        CRITICAL_ROCK, 
        CRITICAL_ELEMENT, 
        CRITICAL_UNDEAD,
        MARIO_TIME_UP, 
        MARIO_REUSE_TIME_CUT,
        SELLRATE_UP, 
        BUYRATE_DOWN, 
        BOOST_POWER,
        BOOST_MAGIC, 
        BOOST_HP,
        BOOST_CRITICAL,
        EXPANSION_POINT_FIX_UP,
        SECT_POINT_PER_UP,
        MATERIAL_POINT_PER_UP,
        FISH_RARE_RATE_FIX_UP, 
        FISH_BIG_RATE_FIX_UP, 
        SEED_GROWTH_FIX_UP,
        SEED_AFFECTION_FIX_UP,
        TRANCE_SPEED_UP, 
        TRANS_DAMAGE_NOCHG_UP, 
        RECYCLE_WOLRDPOINT_UP,
        QUEST_EP_UP,
        AM_FIX_UP, 
        AM_PER_UP,
        EXP_UP,
        JEXP_UP,
        RAREDROP_UP, 
        COMB_BDAMAGE_UP,
        COMB_MDAMAGE_UP, 
        COMB_DAMAGE_UP, 
        COMB_HP_MAX_UP,
        COMB_HP_PER_UP, 
        COMB_MP_MAX_UP, 
        COMB_MP_PER_UP, 
        COMB_SP_MAX_UP, 
        COMB_SP_PER_UP,
        COMB_HMS_MAX_UP,
        COMB_HMS_PER_UP,
        COMB_ATK_FIX_UP, 
        COMB_ATK_PER_UP, 
        COMB_MATK_FIX_UP,
        COMB_MATK_PER_UP, 
        COMB_DEF_FIX_UP,
        COMB_MDEF_FIX_UP,
        COMB_SAVOID_FIX_UP,
        COMB_SAVOID_PER_UP,
        COMB_LAVOID_FIX_UP, 
        COMB_LAVOID_PER_UP, 
        COMB_WEAPON_AV_MAX_UP,
        COMB_WEAPON_AV_PER_UP,
        COMB_TOPS_AV_MAX_UP, 
        COMB_TOPS_AV_PER_UP, 
        COMB_CHEST_AV_MAX_UP, 
        COMB_CHEST_AV_PER_UP, 
        COMB_ALL_AV_MAX_UP,
        COMB_ALL_AV_PER_UP,
        COMB_THROW_DAMAGE_UP,
        COMB_DAMAGE_DOWN, 
        COMB_MON_DAMAGE_DOWN,
        COMB_EXP_UP,
        NONE



        /*HP最大値上昇Plus,//1
        MP最大値上昇Plus,//2
        SP最大値上昇Plus,//3
        HP回復力上昇Perc,//4
        MP回復力上昇Perc,//5
        SP回復力上昇Perc,//6
        STR上昇Plus,//7
        DEX上昇Plus,//8
        INT上昇Plus,//9
        VIT上昇Plus,//10
        AGI上昇Plus,//11
        MAG上昇Plus,//12
        ATK値上昇Plus,//22  13
        MATK値上昇Plus,//23  14
        SHIT値上昇Plus,//24   15
        SHIT値上昇Perc,//25   16
        LHIT値上昇Plus,//26 17
        LHIT値上昇Perc,//27 18
        DEF上昇Plus,//13 19
        武器攻撃力上昇Plus,//28 20 
        武器攻撃力上昇Perc,//29 21
        防具防御力上昇Plus,//30 22
        防具防御力上昇Perc,//14 23
        被物理ダメージ減少Perc,//15 24
        クリティカル上昇Perc,//16 25
        ガード率上昇Perc,//17 26
        ペイロード上昇Perc,//18 27
        キャパシティ上昇Perc,//19 28
        Lv差命中減少軽減Perc,//20 29
        ペット成長率上昇Perc,//21 30*/
    }

    public enum CardSlot
    {
        胸,
        武器,
        服,
    }

    public enum Rarity
    {
        Common = 1,
        Uncommon,
        Rare,
        SuperRare,
        Special,
    }
}